version: '3.8'
services:
  es-master:
    image: elasticsearch:6.8.12
    container_name: es-master    
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-master-datas:/usr/share/elasticsearch/data
      - es-master-logs:/usr/share/elasticsearch/logs
      - es-master-config:/usr/share/elasticsearch/config      
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  es-slave1:
    image: elasticsearch:6.8.12
    container_name: es-slave1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-slave1-datas:/usr/share/elasticsearch/data
      - es-slave1-logs:/usr/share/elasticsearch/logs
      - es-slave1-config:/usr/share/elasticsearch/config
    networks:
      - esnet

volumes:
  es-master-datas:
    name: es-master-datas
  es-slave1-datas:
    name: es-slave1-datas
  es-master-logs:
    name: es-master-logs
  es-slave1-logs:
    name: es-slave1-logs
  es-master-config:
    name: es-master-config
  es-slave1-config:
    name: es-slave1-config

networks:
  esnet:
    name: esnet