version: '3.8'
services:
  es-data2:
    image: elasticsearch:6.8.12
    container_name: es-data2
    network_mode: 'host'
    environment:      
      cluster.name: 'docker-cluster'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
      node.name: 'es-data2'
      node.master: 'false'
      node.data: 'true'
      node.ingest: 'false'
      node.ml: 'false'
      discovery.zen.minimum_master_nodes: 1      
      discovery.zen.ping.unicast.hosts: '192.168.137.54:9201,192.168.137.54:9301'
      network.host: '192.168.137.53'  
      path.data: '/usr/share/elasticsearch/data/01,/usr/share/elasticsearch/data/02,/usr/share/elasticsearch/data/03,/usr/share/elasticsearch/data/04,/usr/share/elasticsearch/data/05,/usr/share/elasticsearch/data/06,/usr/share/elasticsearch/data/07,/usr/share/elasticsearch/data/08,/usr/share/elasticsearch/data/09,/usr/share/elasticsearch/data/10,/usr/share/elasticsearch/data/11,/usr/share/elasticsearch/data/012'
      http.enabled: 'false'
      #network.host: '0.0.0.0'  默认就是0.0.0.0 不确定能否外网物理ip非host模式
      #discovery.zen.ping.unicast.hosts: '发现主机,隔开'
      #indices.fielddata.cache.size: '25%'
      #path.data: '数据存储路径' 默认
      #path.data: /data/01,/data/02     # 如果在path.data中写多个目录用“，”分隔，功能类似于raid 0，而不是做备份
      #cluster.routing.allocation.same_shard.host: true
      #path.logs: ''
      #http.port: 9200默认
      #transport.tcp.port: 9300默认      
      # network.bind_host: 0.0.0.0    这两个参数和上面的host是同样效果
      # network.publish_host: 172.17.3.99   这个是否可以保留外网物理ip
      #node.attr.rack: '备注'      
      #gateway.recover_after_nodes: 1 多数节点才开始实现恢复
      # http.cors.enabled: true  heap等插件需要打开跨域
      # http.cors.allow-origin: "*"
      #indices.query.bool.max_clause_count: 10000  貌似没有说明   应该是索引的计算信息等
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es-data2-datas:/usr/share/elasticsearch/data
      - es-data2-logs:/usr/share/elasticsearch/logs
      - es-data2-cofig:/usr/share/elasticsearch/config
      - /etc/localtime:/etc/localtime
    # networks:
      # - esnet

volumes:
  es-data2-datas:
    name: es-data2-datas
  es-data2-logs:
    name: es-data2-logs
  es-data2-cofig:
    name: es-data2-cofig

# networks:
  # esnet:
    # name: esnet